vlog= input("Enter the title of your vlog today: ")
name= input("Enter your name: ")
age= int(input("Enter your age: "))
sex= input("Enter your sex: ")
exeperience= input("Enter your experience of the day: ")
people_you_met= input("Enter the people you met today: ")
hours_takes_by_bus= float(input("Enter the hours taken by bus today: "))
place= input("Enter the place you are visiting: ")
activity= input("Enter the activity you are doing: ")
acheivement= input("Enter an achievement you accomplished today: ")
food= input("Enter the food you ate today: ")
book= input("Enter the book you read today: ")
sleep= float(input("Enter the hours of sleep you got last night: "))
phone= float(input("Enter the amount of time you spent on your phone today: "))
writing= float(input("Enter the amount of time you spent writing today: "))
coding= int(input("Enter the amount of time you spent coding today: "))
hours_spent_on_instagram= int(input("Enter the hours you spent on Instagram today: "))
hours_spent_on_telegram= int(input("Enter the hours you spent on Telegram today: "))
coffee= int(input("Enter the amount of coffee you drank today: "))
sport= input("Enter the sport you played today: ")
music= input("Enter the music you listened to today: ")
podcast= input("Enter the podcast you listened to today: ")
picture= input("Enter the picture you took today: ")
offer= input("Enter the offer you received today: ")
reading= int(input("Enter the amount of time you spent reading today: "))
print(f"Today, I am vlogging about {vlog}. My name is {name}, I am {age} years old and  I am a {sex}., Today, I had an amazing experience of {exeperience}. I met some wonderful people today, including {people_you_met}. I took a bus for {hours_takes_by_bus} hours to reach {place}, where I engaged in {activity}. One of my achievements today was {acheivement}. For food, I had {food}, and I read the book {book}. I got {sleep} hours of sleep last night and spent {phone} hours on my phone today. I also spent {writing} hours writing and {coding} hours coding. On social media, I spent {hours_spent_on_instagram} hours on Instagram and {hours_spent_on_telegram} hours on Telegram. I drank {coffee} cups of coffee today. For sports, I played {sport}, and for music, I listened to {music}. I also enjoyed the podcast {podcast} and took a picture of {picture}. Lastly, I received an offer for {offer} and spent {reading} hours reading today. Overall, it was a fantastic day filled with memorable experiences and accomplishments!  ")

